---
- name: Setup Docker InvoiceNinja
  hosts: entrapta
  remote_user: jake

  tasks:
  - name: Install docker-py
    become: yes
    pip: 
      name: 
        - docker-py

  - name: Create ninja-net docker network
    docker_network:
      name: ninja-net

  - name: Create Volumes
    docker_volume:
      name: "{{ item }}"
    with_items:
      - ninjadb_data
        # - invoiceninja_storage
        # - invoiceninja_public

  - name: Setup MariaDB 
    docker_container:
      name: ninjadb
      image: mariadb:10
      volumes:
        - ninjadb_data:/var/lib/mysql
      env:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_USER: ninja
        MYSQL_PASSWORD: ninja
        MYSQL_DATABASE: ninja
      networks:
        - name: ninja-net

  - name: Make directories
    file:
      name: "/home/jake/.{{ item }}"
      state: directory
    with_items:
      - invoiceninja_public
      - invoiceninja_storage

  - name: Setup InvoiceNinja
    docker_container:
      name: invoiceninja
      image: invoiceninja/invoiceninja:alpine-4
      volumes:
        - /home/jake/.invoiceninja_public:/var/app/public
        - /home/jake/.invoiceninja_storage:/var/app/storage
      env:
        APP_DEBUG: "true"
        APP_KEY: "{{ app_key }}"
        APP_URL: "https://invoiceninja.skinet.org"
        APP_CIPHER: "AES-256-CBC"
        DB_TYPE: mysql
        DB_HOST: ninja
        DB_USERNAME: ninja
        DB_PASSWORD: ninja
        DB_DATABASE: ninja
        LOG: single
      ports:
        - "9988:9000"
      networks:
        - name: ninja-net

