---
- name: Setup Docker InvoiceNinja
  hosts: earthmanlabs.com
  remote_user: jake

  tasks:
  - name: Install pip
    become: yes
    apt:
      name: 
        - python3
        - python3-pip
        - python
        - python-pip

  - name: Install docker-py
    become: yes
    pip: 
      name: 
        - docker-py

  - name: Create ninja-net docker network
    docker_network:
      name: ninja-net

  - name: Setup MariaDB 
    docker_container:
      name: mariadb
      image: mariadb:10
      volumes:
        - mariadb_data:/var/lib/mysql
      env:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_USER: ninja
        MYSQL_PASSWORD: "{{ mysql_password }}"
        MYSQL_DATABASE: ninja
      networks:
        - name: ninja-net

  - name: Setup InvoiceNinja
    docker_container:
      name: invoiceninja
      image: invoiceninja/invoiceninja
      volumes:
        - /home/jake/invoiceninja/public:/var/app/public
        - /home/jake/invoiceninja/storage:/var/app/storage
      env:
        APP_ENV: production
        APP_DEBUG: "0"
        APP_URL: "https://invoiceninja.earthmanlabs.com"
        APP_CIPHER: "AES-256-CBC"
        DB_TYPE: mysql
        DB_HOST: mariadb
        DB_DATABASE: ninja
        DB_USERNAME: ninja
        DB_PASSWORD: "{{ mysql_password }}"
      ports:
        - "9000:9000"

